server:
  port: 9011
spring:
  application:
    name: consumer-ribbon

eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:7001/eureka/
#    registry-fetch-interval-seconds: 30 //注册中心维护一份只读的服务清单，消费者可修改获取清单的时间间隔
