server:
  port: 9001
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/


#ribbon:
#  ConnectTimeout: 500
#  ReadTimeout: 5000

feign:
  hystrix:
    enabled: true


