spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qzw0518/spring-cloud-practice.git
          search-paths: config-server/configFolder
          username: qiwonder@163.com
          password: qizhiwen945
  security:
    user:
      name: user
      password: user
server:
  port: 11001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


